
#define DATA_WIDTH_CRASHER	4
#define DATA_WIDTH_EATER	4*4
#define DATA_WIDTH_MINE		2
#define DATA_WIDTH_FLOWER	4*7
#define DATA_WIDTH_MISSILE	1
#define DATA_WIDTH_CANON	4*4

#define DATA_WIDTH_OPA		4
#define DATA_WIDTH_ENGINE	3
#define DATA_WIDTH_WEAPON	1
#define DATA_WIDTH_MONSTER	(DATA_WIDTH_CRASHER+DATA_WIDTH_EATER+DATA_WIDTH_MINE+DATA_WIDTH_FLOWER+DATA_WIDTH_MISSILE+DATA_WIDTH_CANON)
#define DATA_WIDTH_BOOM		1

#define DATA_OFFSET_OPA		0
#define DATA_OFFSET_ENGINE	DATA_OFFSET_OPA+DATA_WIDTH_OPA
#define DATA_OFFSET_WEAPON	DATA_OFFSET_ENGINE+DATA_WIDTH_ENGINE
#define DATA_OFFSET_MONSTER	DATA_OFFSET_WEAPON+DATA_WIDTH_WEAPON
#define DATA_OFFSET_BOOM	DATA_OFFSET_MONSTER+DATA_WIDTH_MONSTER

#define DATA_OFFSET_CRASHER 		DATA_OFFSET_MONSTER
#define DATA_OFFSET_EATER 		(DATA_OFFSET_CRASHER+DATA_WIDTH_CRASHER)
#define DATA_OFFSET_MINE 		(DATA_OFFSET_EATER+DATA_WIDTH_EATER)
#define DATA_OFFSET_FLOWER 		(DATA_OFFSET_MINE+DATA_WIDTH_MINE)
#define DATA_OFFSET_MISSILE 		(DATA_OFFSET_FLOWER+DATA_WIDTH_FLOWER)
#define DATA_OFFSET_CANON 		(DATA_OFFSET_MISSILE+DATA_WIDTH_MISSILE)

#define DATA_OFFSET_SMALLWING 		DATA_OFFSET_ENGINE
#define DATA_OFFSET_NORMALENGINE	DATA_OFFSET_SMALLWING+1

#define MAX_VMONSTER	24
#define MAX_MONSTER	24 /*SPRITE_WIDTH_MONSTER*/

// Protection des monstres
#define DESTRUCTION_VCRASHER	5
#define DESTRUCTION_VEATER	1
#define DESTRUCTION_VMINE	3
#define DESTRUCTION_VFLOWER	0
#define DESTRUCTION_VCANON	3

// Rectangle de collision

#define RECT_X_VCRASHER		0
#define RECT_Y_VCRASHER		0
#define RECT_W_VCRASHER		16
#define RECT_H_VCRASHER		16

#define RECT_X_VEATER		2
#define RECT_Y_VEATER		2
#define RECT_W_VEATER		14
#define RECT_H_VEATER		14

#define RECT_X_VMINE		2
#define RECT_Y_VMINE		2
#define RECT_W_VMINE		14
#define RECT_H_VMINE		14

#define RECT_X_VFLOWER		2
#define RECT_Y_VFLOWER		2
#define RECT_W_VFLOWER		14
#define RECT_H_VFLOWER		14

#define RECT_X_VMISSILE		2
#define RECT_Y_VMISSILE		2
#define RECT_W_VMISSILE		4
#define RECT_H_VMISSILE		4

#define RECT_X_VCANON		2
#define RECT_Y_VCANON		2
#define RECT_W_VCANON		14
#define RECT_H_VCANON		10

// Numero de Palette pour propriété

#define	PAL0	0
#define PAL1	1
#define PAL2	2
#define	PAL3	3
#define	PAL4	4
#define	PAL5	5
#define	PAL6	6
#define	PAL7	7

// Fenetre des sprites

#define SPRITE_WIN_UP		16
#define SPRITE_WIN_DOWN		144
#define SPRITE_WIN_RIGHT	160
#define SPRITE_WIN_LEFT		8
