/*

 SPRITEOPA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PtrOpaBank 0

/* Super Gameboy palette 0 */
#define PtrOpaSGBPal0c0 31614
#define PtrOpaSGBPal0c1 0
#define PtrOpaSGBPal0c2 4104
#define PtrOpaSGBPal0c3 6

/* Super Gameboy palette 1 */
#define PtrOpaSGBPal1c0 0
#define PtrOpaSGBPal1c1 0
#define PtrOpaSGBPal1c2 4104
#define PtrOpaSGBPal1c3 6

/* Super Gameboy palette 2 */
#define PtrOpaSGBPal2c0 0
#define PtrOpaSGBPal2c1 0
#define PtrOpaSGBPal2c2 4104
#define PtrOpaSGBPal2c3 6

/* Super Gameboy palette 3 */
#define PtrOpaSGBPal3c0 0
#define PtrOpaSGBPal3c1 0
#define PtrOpaSGBPal3c2 4104
#define PtrOpaSGBPal3c3 6

/* Gameboy Color palette 0 */
#define PtrOpaCGBPal0c0 31775
#define PtrOpaCGBPal0c1 31
#define PtrOpaCGBPal0c2 1023
#define PtrOpaCGBPal0c3 0

/* Gameboy Color palette 1 */
#define PtrOpaCGBPal1c0 31775
#define PtrOpaCGBPal1c1 31
#define PtrOpaCGBPal1c2 992
#define PtrOpaCGBPal1c3 0

/* Gameboy Color palette 2 */
#define PtrOpaCGBPal2c0 31775
#define PtrOpaCGBPal2c1 992
#define PtrOpaCGBPal2c2 640
#define PtrOpaCGBPal2c3 0

/* Gameboy Color palette 3 */
#define PtrOpaCGBPal3c0 31775
#define PtrOpaCGBPal3c1 32736
#define PtrOpaCGBPal3c2 1023
#define PtrOpaCGBPal3c3 0

/* Gameboy Color palette 4 */
#define PtrOpaCGBPal4c0 31775
#define PtrOpaCGBPal4c1 32767
#define PtrOpaCGBPal4c2 13741
#define PtrOpaCGBPal4c3 0

/* Gameboy Color palette 5 */
#define PtrOpaCGBPal5c0 31775
#define PtrOpaCGBPal5c1 32767
#define PtrOpaCGBPal5c2 511
#define PtrOpaCGBPal5c3 0

/* Gameboy Color palette 6 */
#define PtrOpaCGBPal6c0 6108
#define PtrOpaCGBPal6c1 32095
#define PtrOpaCGBPal6c2 31
#define PtrOpaCGBPal6c3 0

/* Gameboy Color palette 7 */
#define PtrOpaCGBPal7c0 31775
#define PtrOpaCGBPal7c1 32767
#define PtrOpaCGBPal7c2 1541
#define PtrOpaCGBPal7c3 0

/* CGB palette entries. */
#define PtrOpaCGB0 0
#define PtrOpaCGB1 1
#define PtrOpaCGB2 3
#define PtrOpaCGB3 2
/* Start of tile array. */
extern unsigned char PtrOpa[];

/* End of SPRITEOPA.H */
