/*

 BLANKMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\SDK\gbz80-gb\2-1-0\GBSam\CrazyZone\logo\logo.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.7

*/

#define PtrBlankMapWidth 32
#define PtrBlankMapHeight 18
#define PtrBlankMapBank 0

extern unsigned char PtrBlankMap[];

/* End of BLANKMAP.H */
