/*

 CRAZYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : CrazyZone.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.7

*/

#define PtrCrazyMapWidth 32
#define PtrCrazyMapHeight 18
#define PtrCrazyMapBank 0

extern unsigned char PtrCrazyMap[];

/* End of CRAZYMAP.H */
