/*

 CRAZYTILE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 200

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PtrCrazyTileBank 0

/* Super Gameboy palette 0 */
#define PtrCrazyTileSGBPal0c0 8724
#define PtrCrazyTileSGBPal0c1 4496
#define PtrCrazyTileSGBPal0c2 4232
#define PtrCrazyTileSGBPal0c3 4

/* Super Gameboy palette 1 */
#define PtrCrazyTileSGBPal1c0 8724
#define PtrCrazyTileSGBPal1c1 4496
#define PtrCrazyTileSGBPal1c2 0
#define PtrCrazyTileSGBPal1c3 0

/* Super Gameboy palette 2 */
#define PtrCrazyTileSGBPal2c0 6610
#define PtrCrazyTileSGBPal2c1 4364
#define PtrCrazyTileSGBPal2c2 0
#define PtrCrazyTileSGBPal2c3 0

/* Super Gameboy palette 3 */
#define PtrCrazyTileSGBPal3c0 5553
#define PtrCrazyTileSGBPal3c1 4364
#define PtrCrazyTileSGBPal3c2 0
#define PtrCrazyTileSGBPal3c3 0

/* Gameboy Color palette 0 */
#define PtrCrazyTileCGBPal0c0 8724
#define PtrCrazyTileCGBPal0c1 4496
#define PtrCrazyTileCGBPal0c2 4232
#define PtrCrazyTileCGBPal0c3 4

/* Gameboy Color palette 1 */
#define PtrCrazyTileCGBPal1c0 8724
#define PtrCrazyTileCGBPal1c1 4496
#define PtrCrazyTileCGBPal1c2 0
#define PtrCrazyTileCGBPal1c3 0

/* Gameboy Color palette 2 */
#define PtrCrazyTileCGBPal2c0 6610
#define PtrCrazyTileCGBPal2c1 4364
#define PtrCrazyTileCGBPal2c2 0
#define PtrCrazyTileCGBPal2c3 0

/* Gameboy Color palette 3 */
#define PtrCrazyTileCGBPal3c0 5553
#define PtrCrazyTileCGBPal3c1 4364
#define PtrCrazyTileCGBPal3c2 0
#define PtrCrazyTileCGBPal3c3 0

/* Gameboy Color palette 4 */
#define PtrCrazyTileCGBPal4c0 8724
#define PtrCrazyTileCGBPal4c1 4496
#define PtrCrazyTileCGBPal4c2 4364
#define PtrCrazyTileCGBPal4c3 0

/* Gameboy Color palette 5 */
#define PtrCrazyTileCGBPal5c0 6610
#define PtrCrazyTileCGBPal5c1 4430
#define PtrCrazyTileCGBPal5c2 0
#define PtrCrazyTileCGBPal5c3 0

/* Gameboy Color palette 6 */
#define PtrCrazyTileCGBPal6c0 8724
#define PtrCrazyTileCGBPal6c1 4430
#define PtrCrazyTileCGBPal6c2 4232
#define PtrCrazyTileCGBPal6c3 0

/* Gameboy Color palette 7 */
#define PtrCrazyTileCGBPal7c0 0
#define PtrCrazyTileCGBPal7c1 4430
#define PtrCrazyTileCGBPal7c2 8724
#define PtrCrazyTileCGBPal7c3 0

/* CGB palette entries. */
#define PtrCrazyTileCGB0 0
#define PtrCrazyTileCGB1 0
#define PtrCrazyTileCGB2 0
#define PtrCrazyTileCGB3 0
#define PtrCrazyTileCGB4 0
#define PtrCrazyTileCGB5 0
#define PtrCrazyTileCGB6 6
#define PtrCrazyTileCGB7 6
#define PtrCrazyTileCGB8 6
#define PtrCrazyTileCGB9 6
#define PtrCrazyTileCGB10 6
#define PtrCrazyTileCGB11 6
#define PtrCrazyTileCGB12 6
#define PtrCrazyTileCGB13 6
#define PtrCrazyTileCGB14 4
#define PtrCrazyTileCGB15 4
#define PtrCrazyTileCGB16 4
#define PtrCrazyTileCGB17 6
#define PtrCrazyTileCGB18 4
#define PtrCrazyTileCGB19 4
#define PtrCrazyTileCGB20 4
#define PtrCrazyTileCGB21 6
#define PtrCrazyTileCGB22 4
#define PtrCrazyTileCGB23 4
#define PtrCrazyTileCGB24 6
#define PtrCrazyTileCGB25 0
#define PtrCrazyTileCGB26 0
#define PtrCrazyTileCGB27 0
#define PtrCrazyTileCGB28 6
#define PtrCrazyTileCGB29 4
#define PtrCrazyTileCGB30 4
#define PtrCrazyTileCGB31 0
#define PtrCrazyTileCGB32 4
#define PtrCrazyTileCGB33 4
#define PtrCrazyTileCGB34 0
#define PtrCrazyTileCGB35 4
#define PtrCrazyTileCGB36 4
#define PtrCrazyTileCGB37 0
#define PtrCrazyTileCGB38 0
#define PtrCrazyTileCGB39 6
#define PtrCrazyTileCGB40 4
#define PtrCrazyTileCGB41 6
#define PtrCrazyTileCGB42 0
#define PtrCrazyTileCGB43 0
#define PtrCrazyTileCGB44 6
#define PtrCrazyTileCGB45 6
#define PtrCrazyTileCGB46 4
#define PtrCrazyTileCGB47 6
#define PtrCrazyTileCGB48 4
#define PtrCrazyTileCGB49 4
#define PtrCrazyTileCGB50 4
#define PtrCrazyTileCGB51 4
#define PtrCrazyTileCGB52 4
#define PtrCrazyTileCGB53 4
#define PtrCrazyTileCGB54 0
#define PtrCrazyTileCGB55 0
#define PtrCrazyTileCGB56 0
#define PtrCrazyTileCGB57 0
#define PtrCrazyTileCGB58 0
#define PtrCrazyTileCGB59 0
#define PtrCrazyTileCGB60 0
#define PtrCrazyTileCGB61 0
#define PtrCrazyTileCGB62 0
#define PtrCrazyTileCGB63 0
#define PtrCrazyTileCGB64 0
#define PtrCrazyTileCGB65 0
#define PtrCrazyTileCGB66 0
#define PtrCrazyTileCGB67 0
#define PtrCrazyTileCGB68 0
#define PtrCrazyTileCGB69 0
#define PtrCrazyTileCGB70 0
#define PtrCrazyTileCGB71 0
#define PtrCrazyTileCGB72 0
#define PtrCrazyTileCGB73 0
#define PtrCrazyTileCGB74 0
#define PtrCrazyTileCGB75 0
#define PtrCrazyTileCGB76 0
#define PtrCrazyTileCGB77 0
#define PtrCrazyTileCGB78 0
#define PtrCrazyTileCGB79 0
#define PtrCrazyTileCGB80 0
#define PtrCrazyTileCGB81 0
#define PtrCrazyTileCGB82 0
#define PtrCrazyTileCGB83 0
#define PtrCrazyTileCGB84 0
#define PtrCrazyTileCGB85 0
#define PtrCrazyTileCGB86 0
#define PtrCrazyTileCGB87 0
#define PtrCrazyTileCGB88 0
#define PtrCrazyTileCGB89 0
#define PtrCrazyTileCGB90 0
#define PtrCrazyTileCGB91 0
#define PtrCrazyTileCGB92 0
#define PtrCrazyTileCGB93 0
#define PtrCrazyTileCGB94 0
#define PtrCrazyTileCGB95 0
#define PtrCrazyTileCGB96 0
#define PtrCrazyTileCGB97 0
#define PtrCrazyTileCGB98 0
#define PtrCrazyTileCGB99 0
#define PtrCrazyTileCGB100 0
#define PtrCrazyTileCGB101 0
#define PtrCrazyTileCGB102 0
#define PtrCrazyTileCGB103 0
#define PtrCrazyTileCGB104 0
#define PtrCrazyTileCGB105 0
#define PtrCrazyTileCGB106 0
#define PtrCrazyTileCGB107 0
#define PtrCrazyTileCGB108 0
#define PtrCrazyTileCGB109 0
#define PtrCrazyTileCGB110 0
#define PtrCrazyTileCGB111 0
#define PtrCrazyTileCGB112 0
#define PtrCrazyTileCGB113 0
#define PtrCrazyTileCGB114 0
#define PtrCrazyTileCGB115 0
#define PtrCrazyTileCGB116 0
#define PtrCrazyTileCGB117 0
#define PtrCrazyTileCGB118 0
#define PtrCrazyTileCGB119 0
#define PtrCrazyTileCGB120 0
#define PtrCrazyTileCGB121 0
#define PtrCrazyTileCGB122 0
#define PtrCrazyTileCGB123 0
#define PtrCrazyTileCGB124 0
#define PtrCrazyTileCGB125 0
#define PtrCrazyTileCGB126 0
#define PtrCrazyTileCGB127 0
#define PtrCrazyTileCGB128 0
#define PtrCrazyTileCGB129 0
#define PtrCrazyTileCGB130 0
#define PtrCrazyTileCGB131 0
#define PtrCrazyTileCGB132 0
#define PtrCrazyTileCGB133 0
#define PtrCrazyTileCGB134 0
#define PtrCrazyTileCGB135 0
#define PtrCrazyTileCGB136 0
#define PtrCrazyTileCGB137 0
#define PtrCrazyTileCGB138 0
#define PtrCrazyTileCGB139 0
#define PtrCrazyTileCGB140 0
#define PtrCrazyTileCGB141 0
#define PtrCrazyTileCGB142 0
#define PtrCrazyTileCGB143 0
#define PtrCrazyTileCGB144 0
#define PtrCrazyTileCGB145 0
#define PtrCrazyTileCGB146 0
#define PtrCrazyTileCGB147 0
#define PtrCrazyTileCGB148 0
#define PtrCrazyTileCGB149 0
#define PtrCrazyTileCGB150 0
#define PtrCrazyTileCGB151 0
#define PtrCrazyTileCGB152 0
#define PtrCrazyTileCGB153 0
#define PtrCrazyTileCGB154 0
#define PtrCrazyTileCGB155 0
#define PtrCrazyTileCGB156 0
#define PtrCrazyTileCGB157 0
#define PtrCrazyTileCGB158 0
#define PtrCrazyTileCGB159 0
#define PtrCrazyTileCGB160 0
#define PtrCrazyTileCGB161 0
#define PtrCrazyTileCGB162 0
#define PtrCrazyTileCGB163 0
#define PtrCrazyTileCGB164 0
#define PtrCrazyTileCGB165 0
#define PtrCrazyTileCGB166 0
#define PtrCrazyTileCGB167 0
#define PtrCrazyTileCGB168 0
#define PtrCrazyTileCGB169 0
#define PtrCrazyTileCGB170 0
#define PtrCrazyTileCGB171 0
#define PtrCrazyTileCGB172 0
#define PtrCrazyTileCGB173 0
#define PtrCrazyTileCGB174 0
#define PtrCrazyTileCGB175 0
#define PtrCrazyTileCGB176 0
#define PtrCrazyTileCGB177 0
#define PtrCrazyTileCGB178 0
#define PtrCrazyTileCGB179 0
#define PtrCrazyTileCGB180 0
#define PtrCrazyTileCGB181 0
#define PtrCrazyTileCGB182 0
#define PtrCrazyTileCGB183 0
#define PtrCrazyTileCGB184 0
#define PtrCrazyTileCGB185 0
#define PtrCrazyTileCGB186 0
#define PtrCrazyTileCGB187 0
#define PtrCrazyTileCGB188 0
#define PtrCrazyTileCGB189 0
#define PtrCrazyTileCGB190 0
#define PtrCrazyTileCGB191 0
#define PtrCrazyTileCGB192 0
#define PtrCrazyTileCGB193 0
#define PtrCrazyTileCGB194 0
#define PtrCrazyTileCGB195 0
#define PtrCrazyTileCGB196 0
#define PtrCrazyTileCGB197 0
#define PtrCrazyTileCGB198 0
#define PtrCrazyTileCGB199 0
#define PtrCrazyTileCGB200 0
/* Start of tile array. */
extern unsigned char PtrCrazyTile[];

/* End of CRAZYTILE.H */
