/*

 LOGOMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\SDK\gbz80-gb\2-1-0\GBSam\CrazyZone\logo\logo.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.7

*/

#define PtrLogoMapWidth 32
#define PtrLogoMapHeight 18
#define PtrLogoMapBank 0

extern unsigned char PtrLogoMap[];

/* End of LOGOMAP.H */
