/*

 LOGOTILE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 88

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PtrLogoTileBank 0

/* Super Gameboy palette 0 */
#define PtrLogoTileSGBPal0c0 16894
#define PtrLogoTileSGBPal0c1 1024
#define PtrLogoTileSGBPal0c2 1
#define PtrLogoTileSGBPal0c3 0

/* Super Gameboy palette 1 */
#define PtrLogoTileSGBPal1c0 20127
#define PtrLogoTileSGBPal1c1 8478
#define PtrLogoTileSGBPal1c2 1080
#define PtrLogoTileSGBPal1c3 1

/* Super Gameboy palette 2 */
#define PtrLogoTileSGBPal2c0 23262
#define PtrLogoTileSGBPal2c1 16926
#define PtrLogoTileSGBPal2c2 9534
#define PtrLogoTileSGBPal2c3 1

/* Super Gameboy palette 3 */
#define PtrLogoTileSGBPal3c0 22238
#define PtrLogoTileSGBPal3c1 13758
#define PtrLogoTileSGBPal3c2 7421
#define PtrLogoTileSGBPal3c3 1

/* Gameboy Color palette 0 */
#define PtrLogoTileCGBPal0c0 16894
#define PtrLogoTileCGBPal0c1 1024
#define PtrLogoTileCGBPal0c2 1
#define PtrLogoTileCGBPal0c3 0

/* Gameboy Color palette 1 */
#define PtrLogoTileCGBPal1c0 20127
#define PtrLogoTileCGBPal1c1 8478
#define PtrLogoTileCGBPal1c2 1080
#define PtrLogoTileCGBPal1c3 1

/* Gameboy Color palette 2 */
#define PtrLogoTileCGBPal2c0 23262
#define PtrLogoTileCGBPal2c1 16926
#define PtrLogoTileCGBPal2c2 9534
#define PtrLogoTileCGBPal2c3 1

/* Gameboy Color palette 3 */
#define PtrLogoTileCGBPal3c0 22238
#define PtrLogoTileCGBPal3c1 13758
#define PtrLogoTileCGBPal3c2 7421
#define PtrLogoTileCGBPal3c3 1

/* Gameboy Color palette 4 */
#define PtrLogoTileCGBPal4c0 21182
#define PtrLogoTileCGBPal4c1 14814
#define PtrLogoTileCGBPal4c2 7420
#define PtrLogoTileCGBPal4c3 1

/* Gameboy Color palette 5 */
#define PtrLogoTileCGBPal5c0 22207
#define PtrLogoTileCGBPal5c1 12702
#define PtrLogoTileCGBPal5c2 6364
#define PtrLogoTileCGBPal5c3 1

/* Gameboy Color palette 6 */
#define PtrLogoTileCGBPal6c0 22239
#define PtrLogoTileCGBPal6c1 15870
#define PtrLogoTileCGBPal6c2 6364
#define PtrLogoTileCGBPal6c3 2

/* Gameboy Color palette 7 */
#define PtrLogoTileCGBPal7c0 21150
#define PtrLogoTileCGBPal7c1 13758
#define PtrLogoTileCGBPal7c2 4248
#define PtrLogoTileCGBPal7c3 0

/* CGB palette entries. */
#define PtrLogoTileCGB0 7
#define PtrLogoTileCGB1 7
#define PtrLogoTileCGB2 7
#define PtrLogoTileCGB3 7
#define PtrLogoTileCGB4 7
#define PtrLogoTileCGB5 7
#define PtrLogoTileCGB6 1
#define PtrLogoTileCGB7 1
#define PtrLogoTileCGB8 7
#define PtrLogoTileCGB9 1
#define PtrLogoTileCGB10 1
#define PtrLogoTileCGB11 7
#define PtrLogoTileCGB12 1
#define PtrLogoTileCGB13 2
#define PtrLogoTileCGB14 7
#define PtrLogoTileCGB15 7
#define PtrLogoTileCGB16 7
#define PtrLogoTileCGB17 7
#define PtrLogoTileCGB18 7
#define PtrLogoTileCGB19 7
#define PtrLogoTileCGB20 7
#define PtrLogoTileCGB21 7
#define PtrLogoTileCGB22 7
#define PtrLogoTileCGB23 7
#define PtrLogoTileCGB24 1
#define PtrLogoTileCGB25 1
#define PtrLogoTileCGB26 2
#define PtrLogoTileCGB27 2
#define PtrLogoTileCGB28 7
#define PtrLogoTileCGB29 5
#define PtrLogoTileCGB30 5
#define PtrLogoTileCGB31 1
#define PtrLogoTileCGB32 1
#define PtrLogoTileCGB33 1
#define PtrLogoTileCGB34 1
#define PtrLogoTileCGB35 2
#define PtrLogoTileCGB36 7
#define PtrLogoTileCGB37 7
#define PtrLogoTileCGB38 7
#define PtrLogoTileCGB39 7
#define PtrLogoTileCGB40 7
#define PtrLogoTileCGB41 7
#define PtrLogoTileCGB42 7
#define PtrLogoTileCGB43 7
#define PtrLogoTileCGB44 1
#define PtrLogoTileCGB45 1
#define PtrLogoTileCGB46 1
#define PtrLogoTileCGB47 3
#define PtrLogoTileCGB48 4
#define PtrLogoTileCGB49 2
#define PtrLogoTileCGB50 4
#define PtrLogoTileCGB51 4
#define PtrLogoTileCGB52 4
#define PtrLogoTileCGB53 1
#define PtrLogoTileCGB54 1
#define PtrLogoTileCGB55 5
#define PtrLogoTileCGB56 1
#define PtrLogoTileCGB57 7
#define PtrLogoTileCGB58 7
#define PtrLogoTileCGB59 7
#define PtrLogoTileCGB60 7
#define PtrLogoTileCGB61 7
#define PtrLogoTileCGB62 7
#define PtrLogoTileCGB63 1
#define PtrLogoTileCGB64 1
#define PtrLogoTileCGB65 1
#define PtrLogoTileCGB66 2
#define PtrLogoTileCGB67 2
#define PtrLogoTileCGB68 2
#define PtrLogoTileCGB69 3
#define PtrLogoTileCGB70 2
#define PtrLogoTileCGB71 2
#define PtrLogoTileCGB72 2
#define PtrLogoTileCGB73 2
#define PtrLogoTileCGB74 7
#define PtrLogoTileCGB75 1
#define PtrLogoTileCGB76 1
#define PtrLogoTileCGB77 7
#define PtrLogoTileCGB78 7
#define PtrLogoTileCGB79 7
#define PtrLogoTileCGB80 0
#define PtrLogoTileCGB81 0
#define PtrLogoTileCGB82 0
#define PtrLogoTileCGB83 0
#define PtrLogoTileCGB84 0
#define PtrLogoTileCGB85 0
#define PtrLogoTileCGB86 0
#define PtrLogoTileCGB87 0
#define PtrLogoTileCGB88 0
/* Start of tile array. */
extern unsigned char PtrLogoTile[];

/* End of LOGOTILE.H */
