/*

 TEXTTILE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 89

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PtrTextTileBank 0

/* Super Gameboy palette 0 */
#define PtrTextTileSGBPal0c0 6108
#define PtrTextTileSGBPal0c1 8935
#define PtrTextTileSGBPal0c2 6596
#define PtrTextTileSGBPal0c3 6368

/* Super Gameboy palette 1 */
#define PtrTextTileSGBPal1c0 6108
#define PtrTextTileSGBPal1c1 8935
#define PtrTextTileSGBPal1c2 6596
#define PtrTextTileSGBPal1c3 6368

/* Super Gameboy palette 2 */
#define PtrTextTileSGBPal2c0 6108
#define PtrTextTileSGBPal2c1 8935
#define PtrTextTileSGBPal2c2 6596
#define PtrTextTileSGBPal2c3 6368

/* Super Gameboy palette 3 */
#define PtrTextTileSGBPal3c0 6108
#define PtrTextTileSGBPal3c1 8935
#define PtrTextTileSGBPal3c2 6596
#define PtrTextTileSGBPal3c3 6368

/* Gameboy Color palette 0 */
#define PtrTextTileCGBPal0c0 6108
#define PtrTextTileCGBPal0c1 28637
#define PtrTextTileCGBPal0c2 2431
#define PtrTextTileCGBPal0c3 0

/* Gameboy Color palette 1 */
#define PtrTextTileCGBPal1c0 6108
#define PtrTextTileCGBPal1c1 20480
#define PtrTextTileCGBPal1c2 3487
#define PtrTextTileCGBPal1c3 0

/* Gameboy Color palette 2 */
#define PtrTextTileCGBPal2c0 6108
#define PtrTextTileCGBPal2c1 8935
#define PtrTextTileCGBPal2c2 6596
#define PtrTextTileCGBPal2c3 0

/* Gameboy Color palette 3 */
#define PtrTextTileCGBPal3c0 32767
#define PtrTextTileCGBPal3c1 31
#define PtrTextTileCGBPal3c2 6596
#define PtrTextTileCGBPal3c3 6368

/* Gameboy Color palette 4 */
#define PtrTextTileCGBPal4c0 6108
#define PtrTextTileCGBPal4c1 8935
#define PtrTextTileCGBPal4c2 6596
#define PtrTextTileCGBPal4c3 6368

/* Gameboy Color palette 5 */
#define PtrTextTileCGBPal5c0 6108
#define PtrTextTileCGBPal5c1 8935
#define PtrTextTileCGBPal5c2 6596
#define PtrTextTileCGBPal5c3 6368

/* Gameboy Color palette 6 */
#define PtrTextTileCGBPal6c0 6108
#define PtrTextTileCGBPal6c1 8935
#define PtrTextTileCGBPal6c2 6596
#define PtrTextTileCGBPal6c3 6368

/* Gameboy Color palette 7 */
#define PtrTextTileCGBPal7c0 6108
#define PtrTextTileCGBPal7c1 8935
#define PtrTextTileCGBPal7c2 6596
#define PtrTextTileCGBPal7c3 6368

/* CGB palette entries. */
#define PtrTextTileCGB0 0
#define PtrTextTileCGB1 0
#define PtrTextTileCGB2 0
#define PtrTextTileCGB3 0
#define PtrTextTileCGB4 0
#define PtrTextTileCGB5 0
#define PtrTextTileCGB6 0
#define PtrTextTileCGB7 0
#define PtrTextTileCGB8 0
#define PtrTextTileCGB9 0
#define PtrTextTileCGB10 0
#define PtrTextTileCGB11 0
#define PtrTextTileCGB12 0
#define PtrTextTileCGB13 0
#define PtrTextTileCGB14 0
#define PtrTextTileCGB15 0
#define PtrTextTileCGB16 0
#define PtrTextTileCGB17 0
#define PtrTextTileCGB18 0
#define PtrTextTileCGB19 0
#define PtrTextTileCGB20 0
#define PtrTextTileCGB21 0
#define PtrTextTileCGB22 0
#define PtrTextTileCGB23 0
#define PtrTextTileCGB24 0
#define PtrTextTileCGB25 0
#define PtrTextTileCGB26 0
#define PtrTextTileCGB27 1
#define PtrTextTileCGB28 0
#define PtrTextTileCGB29 0
#define PtrTextTileCGB30 0
#define PtrTextTileCGB31 0
#define PtrTextTileCGB32 0
#define PtrTextTileCGB33 0
#define PtrTextTileCGB34 0
#define PtrTextTileCGB35 0
#define PtrTextTileCGB36 0
#define PtrTextTileCGB37 0
#define PtrTextTileCGB38 0
#define PtrTextTileCGB39 0
#define PtrTextTileCGB40 0
#define PtrTextTileCGB41 0
#define PtrTextTileCGB42 2
#define PtrTextTileCGB43 0
#define PtrTextTileCGB44 0
#define PtrTextTileCGB45 2
#define PtrTextTileCGB46 2
#define PtrTextTileCGB47 2
#define PtrTextTileCGB48 2
#define PtrTextTileCGB49 2
#define PtrTextTileCGB50 2
#define PtrTextTileCGB51 2
#define PtrTextTileCGB52 2
#define PtrTextTileCGB53 2
#define PtrTextTileCGB54 2
#define PtrTextTileCGB55 2
#define PtrTextTileCGB56 2
#define PtrTextTileCGB57 2
#define PtrTextTileCGB58 2
#define PtrTextTileCGB59 2
#define PtrTextTileCGB60 2
#define PtrTextTileCGB61 2
#define PtrTextTileCGB62 2
#define PtrTextTileCGB63 2
#define PtrTextTileCGB64 2
#define PtrTextTileCGB65 2
#define PtrTextTileCGB66 2
#define PtrTextTileCGB67 2
#define PtrTextTileCGB68 2
#define PtrTextTileCGB69 2
#define PtrTextTileCGB70 2
#define PtrTextTileCGB71 2
#define PtrTextTileCGB72 0
#define PtrTextTileCGB73 2
#define PtrTextTileCGB74 2
#define PtrTextTileCGB75 2
#define PtrTextTileCGB76 2
#define PtrTextTileCGB77 0
#define PtrTextTileCGB78 0
#define PtrTextTileCGB79 0
#define PtrTextTileCGB80 0
#define PtrTextTileCGB81 0
#define PtrTextTileCGB82 0
#define PtrTextTileCGB83 0
#define PtrTextTileCGB84 0
#define PtrTextTileCGB85 0
#define PtrTextTileCGB86 0
#define PtrTextTileCGB87 0
#define PtrTextTileCGB88 0
#define PtrTextTileCGB89 0
/* Start of tile array. */
extern unsigned char PtrTextTile[];

/* End of TEXTTILE.H */
