/*

 TEXTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\SDK\gbz80-gb\2-1-0\GBSam\CrazyZone\logo\Text.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.7

*/

#define PtrTextMapWidth 20
#define PtrTextMapHeight 18
#define PtrTextMapBank 0

extern unsigned char PtrTextMap[];

/* End of TEXTMAP.H */
