/*

 MAPLEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 305 x 17
   Tile set      : C:\SDK\gbz80-gb\2-1-0\GBSam\CrazyZone\Scroll\Level1\TileLevel1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.7

*/

#define PtrMapLevel1Width 305
#define PtrMapLevel1Height 17
#define PtrMapLevel1Bank 0

extern unsigned char PtrMapLevel1[];

/* End of MAPLEVEL1.H */
