/*

 TILELEVEL1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 99

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PtrTileLevel1Bank 0

/* Super Gameboy palette 0 */
#define PtrTileLevel1SGBPal0c0 6108
#define PtrTileLevel1SGBPal0c1 8935
#define PtrTileLevel1SGBPal0c2 6596
#define PtrTileLevel1SGBPal0c3 6368

/* Super Gameboy palette 1 */
#define PtrTileLevel1SGBPal1c0 6108
#define PtrTileLevel1SGBPal1c1 8935
#define PtrTileLevel1SGBPal1c2 6596
#define PtrTileLevel1SGBPal1c3 6368

/* Super Gameboy palette 2 */
#define PtrTileLevel1SGBPal2c0 6108
#define PtrTileLevel1SGBPal2c1 8935
#define PtrTileLevel1SGBPal2c2 6596
#define PtrTileLevel1SGBPal2c3 6368

/* Super Gameboy palette 3 */
#define PtrTileLevel1SGBPal3c0 6108
#define PtrTileLevel1SGBPal3c1 8935
#define PtrTileLevel1SGBPal3c2 6596
#define PtrTileLevel1SGBPal3c3 6368

/* Gameboy Color palette 0 */
#define PtrTileLevel1CGBPal0c0 8935
#define PtrTileLevel1CGBPal0c1 7781
#define PtrTileLevel1CGBPal0c2 6596
#define PtrTileLevel1CGBPal0c3 0

/* Gameboy Color palette 1 */
#define PtrTileLevel1CGBPal1c0 0
#define PtrTileLevel1CGBPal1c1 572
#define PtrTileLevel1CGBPal1c2 335
#define PtrTileLevel1CGBPal1c3 12754

/* Gameboy Color palette 2 */
#define PtrTileLevel1CGBPal2c0 31744
#define PtrTileLevel1CGBPal2c1 15855
#define PtrTileLevel1CGBPal2c2 32767
#define PtrTileLevel1CGBPal2c3 0

/* Gameboy Color palette 3 */
#define PtrTileLevel1CGBPal3c0 31744
#define PtrTileLevel1CGBPal3c1 19040
#define PtrTileLevel1CGBPal3c2 26144
#define PtrTileLevel1CGBPal3c3 31706

/* Gameboy Color palette 4 */
#define PtrTileLevel1CGBPal4c0 10057
#define PtrTileLevel1CGBPal4c1 8935
#define PtrTileLevel1CGBPal4c2 7781
#define PtrTileLevel1CGBPal4c3 0

/* Gameboy Color palette 5 */
#define PtrTileLevel1CGBPal5c0 19040
#define PtrTileLevel1CGBPal5c1 8935
#define PtrTileLevel1CGBPal5c2 6596
#define PtrTileLevel1CGBPal5c3 0

/* Gameboy Color palette 6 */
#define PtrTileLevel1CGBPal6c0 31744
#define PtrTileLevel1CGBPal6c1 1023
#define PtrTileLevel1CGBPal6c2 351
#define PtrTileLevel1CGBPal6c3 0

/* Gameboy Color palette 7 */
#define PtrTileLevel1CGBPal7c0 32767
#define PtrTileLevel1CGBPal7c1 31
#define PtrTileLevel1CGBPal7c2 20
#define PtrTileLevel1CGBPal7c3 0

/* CGB palette entries. */
#define PtrTileLevel1CGB0 2
#define PtrTileLevel1CGB1 3
#define PtrTileLevel1CGB2 3
#define PtrTileLevel1CGB3 3
#define PtrTileLevel1CGB4 5
#define PtrTileLevel1CGB5 5
#define PtrTileLevel1CGB6 2
#define PtrTileLevel1CGB7 5
#define PtrTileLevel1CGB8 2
#define PtrTileLevel1CGB9 5
#define PtrTileLevel1CGB10 6
#define PtrTileLevel1CGB11 2
#define PtrTileLevel1CGB12 2
#define PtrTileLevel1CGB13 6
#define PtrTileLevel1CGB14 6
#define PtrTileLevel1CGB15 6
#define PtrTileLevel1CGB16 6
#define PtrTileLevel1CGB17 2
#define PtrTileLevel1CGB18 2
#define PtrTileLevel1CGB19 7
#define PtrTileLevel1CGB20 7
#define PtrTileLevel1CGB21 2
#define PtrTileLevel1CGB22 2
#define PtrTileLevel1CGB23 2
#define PtrTileLevel1CGB24 3
#define PtrTileLevel1CGB25 3
#define PtrTileLevel1CGB26 2
#define PtrTileLevel1CGB27 3
#define PtrTileLevel1CGB28 6
#define PtrTileLevel1CGB29 6
#define PtrTileLevel1CGB30 6
#define PtrTileLevel1CGB31 6
#define PtrTileLevel1CGB32 2
#define PtrTileLevel1CGB33 0
#define PtrTileLevel1CGB34 0
#define PtrTileLevel1CGB35 4
#define PtrTileLevel1CGB36 4
#define PtrTileLevel1CGB37 0
#define PtrTileLevel1CGB38 0
#define PtrTileLevel1CGB39 1
#define PtrTileLevel1CGB40 1
#define PtrTileLevel1CGB41 4
#define PtrTileLevel1CGB42 4
#define PtrTileLevel1CGB43 1
#define PtrTileLevel1CGB44 1
#define PtrTileLevel1CGB45 4
#define PtrTileLevel1CGB46 4
#define PtrTileLevel1CGB47 7
#define PtrTileLevel1CGB48 7
#define PtrTileLevel1CGB49 6
#define PtrTileLevel1CGB50 2
#define PtrTileLevel1CGB51 6
#define PtrTileLevel1CGB52 6
#define PtrTileLevel1CGB53 6
#define PtrTileLevel1CGB54 6
#define PtrTileLevel1CGB55 6
#define PtrTileLevel1CGB56 6
#define PtrTileLevel1CGB57 6
#define PtrTileLevel1CGB58 6
#define PtrTileLevel1CGB59 6
#define PtrTileLevel1CGB60 6
#define PtrTileLevel1CGB61 0
#define PtrTileLevel1CGB62 1
#define PtrTileLevel1CGB63 1
#define PtrTileLevel1CGB64 1
#define PtrTileLevel1CGB65 1
#define PtrTileLevel1CGB66 1
#define PtrTileLevel1CGB67 1
#define PtrTileLevel1CGB68 1
#define PtrTileLevel1CGB69 1
#define PtrTileLevel1CGB70 6
#define PtrTileLevel1CGB71 1
#define PtrTileLevel1CGB72 1
#define PtrTileLevel1CGB73 6
#define PtrTileLevel1CGB74 6
#define PtrTileLevel1CGB75 6
#define PtrTileLevel1CGB76 6
#define PtrTileLevel1CGB77 6
#define PtrTileLevel1CGB78 6
#define PtrTileLevel1CGB79 6
#define PtrTileLevel1CGB80 6
#define PtrTileLevel1CGB81 6
#define PtrTileLevel1CGB82 6
#define PtrTileLevel1CGB83 6
#define PtrTileLevel1CGB84 6
#define PtrTileLevel1CGB85 6
#define PtrTileLevel1CGB86 6
#define PtrTileLevel1CGB87 6
#define PtrTileLevel1CGB88 6
#define PtrTileLevel1CGB89 6
#define PtrTileLevel1CGB90 6
#define PtrTileLevel1CGB91 6
#define PtrTileLevel1CGB92 6
#define PtrTileLevel1CGB93 6
#define PtrTileLevel1CGB94 6
#define PtrTileLevel1CGB95 6
#define PtrTileLevel1CGB96 6
#define PtrTileLevel1CGB97 6
#define PtrTileLevel1CGB98 6
#define PtrTileLevel1CGB99 6
/* Start of tile array. */
extern unsigned char PtrTileLevel1[];

/* End of TILELEVEL1.H */
