/*

 MAPLEVEL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 305 x 17
   Tile set      : TileLevel2.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.7

*/

#define PtrMapLevel2Width 305
#define PtrMapLevel2Height 17
#define PtrMapLevel2Bank 0

extern unsigned char PtrMapLevel2[];

/* End of MAPLEVEL2.H */
