/*

 TILELEVEL2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 99

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PtrTileLevel2Bank 0

/* Super Gameboy palette 0 */
#define PtrTileLevel2SGBPal0c0 6076
#define PtrTileLevel2SGBPal0c1 8935
#define PtrTileLevel2SGBPal0c2 6596
#define PtrTileLevel2SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PtrTileLevel2SGBPal1c0 6076
#define PtrTileLevel2SGBPal1c1 8935
#define PtrTileLevel2SGBPal1c2 6596
#define PtrTileLevel2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PtrTileLevel2SGBPal2c0 6076
#define PtrTileLevel2SGBPal2c1 8935
#define PtrTileLevel2SGBPal2c2 6596
#define PtrTileLevel2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PtrTileLevel2SGBPal3c0 6076
#define PtrTileLevel2SGBPal3c1 8935
#define PtrTileLevel2SGBPal3c2 6596
#define PtrTileLevel2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PtrTileLevel2CGBPal0c0 15360
#define PtrTileLevel2CGBPal0c1 32767
#define PtrTileLevel2CGBPal0c2 476
#define PtrTileLevel2CGBPal0c3 0

/* Gameboy Color palette 1 */
#define PtrTileLevel2CGBPal1c0 32767
#define PtrTileLevel2CGBPal1c1 31
#define PtrTileLevel2CGBPal1c2 20
#define PtrTileLevel2CGBPal1c3 0

/* Gameboy Color palette 2 */
#define PtrTileLevel2CGBPal2c0 31744
#define PtrTileLevel2CGBPal2c1 31700
#define PtrTileLevel2CGBPal2c2 32614
#define PtrTileLevel2CGBPal2c3 0

/* Gameboy Color palette 3 */
#define PtrTileLevel2CGBPal3c0 32767
#define PtrTileLevel2CGBPal3c1 31700
#define PtrTileLevel2CGBPal3c2 32614
#define PtrTileLevel2CGBPal3c3 0

/* Gameboy Color palette 4 */
#define PtrTileLevel2CGBPal4c0 863
#define PtrTileLevel2CGBPal4c1 826
#define PtrTileLevel2CGBPal4c2 598
#define PtrTileLevel2CGBPal4c3 0

/* Gameboy Color palette 5 */
#define PtrTileLevel2CGBPal5c0 15360
#define PtrTileLevel2CGBPal5c1 32767
#define PtrTileLevel2CGBPal5c2 15855
#define PtrTileLevel2CGBPal5c3 0

/* Gameboy Color palette 6 */
#define PtrTileLevel2CGBPal6c0 15360
#define PtrTileLevel2CGBPal6c1 32246
#define PtrTileLevel2CGBPal6c2 32614
#define PtrTileLevel2CGBPal6c3 32767

/* Gameboy Color palette 7 */
#define PtrTileLevel2CGBPal7c0 31744
#define PtrTileLevel2CGBPal7c1 32246
#define PtrTileLevel2CGBPal7c2 32614
#define PtrTileLevel2CGBPal7c3 32767

/* CGB palette entries. */
#define PtrTileLevel2CGB0 0
#define PtrTileLevel2CGB1 0
#define PtrTileLevel2CGB2 4
#define PtrTileLevel2CGB3 6
#define PtrTileLevel2CGB4 6
#define PtrTileLevel2CGB5 0
#define PtrTileLevel2CGB6 0
#define PtrTileLevel2CGB7 2
#define PtrTileLevel2CGB8 2
#define PtrTileLevel2CGB9 1
#define PtrTileLevel2CGB10 1
#define PtrTileLevel2CGB11 5
#define PtrTileLevel2CGB12 5
#define PtrTileLevel2CGB13 0
#define PtrTileLevel2CGB14 0
#define PtrTileLevel2CGB15 0
#define PtrTileLevel2CGB16 0
#define PtrTileLevel2CGB17 0
#define PtrTileLevel2CGB18 0
#define PtrTileLevel2CGB19 0
#define PtrTileLevel2CGB20 0
#define PtrTileLevel2CGB21 0
#define PtrTileLevel2CGB22 0
#define PtrTileLevel2CGB23 0
#define PtrTileLevel2CGB24 0
#define PtrTileLevel2CGB25 0
#define PtrTileLevel2CGB26 0
#define PtrTileLevel2CGB27 0
#define PtrTileLevel2CGB28 0
#define PtrTileLevel2CGB29 0
#define PtrTileLevel2CGB30 0
#define PtrTileLevel2CGB31 0
#define PtrTileLevel2CGB32 3
#define PtrTileLevel2CGB33 4
#define PtrTileLevel2CGB34 3
#define PtrTileLevel2CGB35 3
#define PtrTileLevel2CGB36 3
#define PtrTileLevel2CGB37 3
#define PtrTileLevel2CGB38 3
#define PtrTileLevel2CGB39 3
#define PtrTileLevel2CGB40 1
#define PtrTileLevel2CGB41 3
#define PtrTileLevel2CGB42 3
#define PtrTileLevel2CGB43 3
#define PtrTileLevel2CGB44 3
#define PtrTileLevel2CGB45 4
#define PtrTileLevel2CGB46 4
#define PtrTileLevel2CGB47 1
#define PtrTileLevel2CGB48 1
#define PtrTileLevel2CGB49 3
#define PtrTileLevel2CGB50 3
#define PtrTileLevel2CGB51 0
#define PtrTileLevel2CGB52 0
#define PtrTileLevel2CGB53 0
#define PtrTileLevel2CGB54 0
#define PtrTileLevel2CGB55 0
#define PtrTileLevel2CGB56 0
#define PtrTileLevel2CGB57 0
#define PtrTileLevel2CGB58 0
#define PtrTileLevel2CGB59 0
#define PtrTileLevel2CGB60 0
#define PtrTileLevel2CGB61 4
#define PtrTileLevel2CGB62 7
#define PtrTileLevel2CGB63 7
#define PtrTileLevel2CGB64 7
#define PtrTileLevel2CGB65 7
#define PtrTileLevel2CGB66 6
#define PtrTileLevel2CGB67 7
#define PtrTileLevel2CGB68 7
#define PtrTileLevel2CGB69 7
#define PtrTileLevel2CGB70 0
#define PtrTileLevel2CGB71 7
#define PtrTileLevel2CGB72 7
#define PtrTileLevel2CGB73 0
#define PtrTileLevel2CGB74 0
#define PtrTileLevel2CGB75 0
#define PtrTileLevel2CGB76 0
#define PtrTileLevel2CGB77 0
#define PtrTileLevel2CGB78 0
#define PtrTileLevel2CGB79 0
#define PtrTileLevel2CGB80 0
#define PtrTileLevel2CGB81 0
#define PtrTileLevel2CGB82 0
#define PtrTileLevel2CGB83 0
#define PtrTileLevel2CGB84 0
#define PtrTileLevel2CGB85 0
#define PtrTileLevel2CGB86 0
#define PtrTileLevel2CGB87 0
#define PtrTileLevel2CGB88 0
#define PtrTileLevel2CGB89 0
#define PtrTileLevel2CGB90 0
#define PtrTileLevel2CGB91 0
#define PtrTileLevel2CGB92 0
#define PtrTileLevel2CGB93 0
#define PtrTileLevel2CGB94 0
#define PtrTileLevel2CGB95 0
#define PtrTileLevel2CGB96 0
#define PtrTileLevel2CGB97 0
#define PtrTileLevel2CGB98 0
#define PtrTileLevel2CGB99 0
/* Start of tile array. */
extern unsigned char PtrTileLevel2[];

/* End of TILELEVEL2.H */
