/*

 SPRITEBOOM.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.0

*/

/* Start of tile array. */
unsigned char PtrBoom[] =
{
  0x18,0x18,0x27,0x3F,0x61,0x7F,0x82,0xFE,
  0x42,0x7E,0x21,0x3F,0x2F,0x3F,0x30,0x30
};

/* End of SPRITEBOOM.C */
