/*

 SPRITEBOOM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.0

*/


/* Bank of tiles. */
#define PtrBoomBank 0
/* Start of tile array. */
extern unsigned char PtrBoom[];

/* End of SPRITEBOOM.H */
