/*

 WINDOWMAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\SDK\gbz80-gb\2-1-0\GBSam\CrazyZone\Scroll\Level1\TileLevel1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.7

*/

#define PtrWindowMapWidth 20
#define PtrWindowMapHeight 18
#define PtrWindowMapBank 0

extern unsigned char PtrWindowMap[];

/* End of WINDOWMAP1.H */
