/*

 WINDOW.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.0

*/


/* Bank of tiles. */
#define PtrWindowBank 0

/* Super Gameboy palette 0 */
#define PtrWindowSGBPal0c0 6108
#define PtrWindowSGBPal0c1 8935
#define PtrWindowSGBPal0c2 6596
#define PtrWindowSGBPal0c3 6368

/* Super Gameboy palette 1 */
#define PtrWindowSGBPal1c0 6108
#define PtrWindowSGBPal1c1 8935
#define PtrWindowSGBPal1c2 6596
#define PtrWindowSGBPal1c3 6368

/* Super Gameboy palette 2 */
#define PtrWindowSGBPal2c0 6108
#define PtrWindowSGBPal2c1 8935
#define PtrWindowSGBPal2c2 6596
#define PtrWindowSGBPal2c3 6368

/* Super Gameboy palette 3 */
#define PtrWindowSGBPal3c0 6108
#define PtrWindowSGBPal3c1 8935
#define PtrWindowSGBPal3c2 6596
#define PtrWindowSGBPal3c3 6368

/* Gameboy Color palette 0 */
#define PtrWindowCGBPal0c0 8935
#define PtrWindowCGBPal0c1 7781
#define PtrWindowCGBPal0c2 6596
#define PtrWindowCGBPal0c3 0

/* Gameboy Color palette 1 */
#define PtrWindowCGBPal1c0 601
#define PtrWindowCGBPal1c1 471
#define PtrWindowCGBPal1c2 6596
#define PtrWindowCGBPal1c3 0

/* Gameboy Color palette 2 */
#define PtrWindowCGBPal2c0 32192
#define PtrWindowCGBPal2c1 31
#define PtrWindowCGBPal2c2 10
#define PtrWindowCGBPal2c3 0

/* Gameboy Color palette 3 */
#define PtrWindowCGBPal3c0 32192
#define PtrWindowCGBPal3c1 19040
#define PtrWindowCGBPal3c2 26144
#define PtrWindowCGBPal3c3 31706

/* Gameboy Color palette 4 */
#define PtrWindowCGBPal4c0 10057
#define PtrWindowCGBPal4c1 8935
#define PtrWindowCGBPal4c2 7781
#define PtrWindowCGBPal4c3 0

/* Gameboy Color palette 5 */
#define PtrWindowCGBPal5c0 19040
#define PtrWindowCGBPal5c1 8935
#define PtrWindowCGBPal5c2 6596
#define PtrWindowCGBPal5c3 0

/* Gameboy Color palette 6 */
#define PtrWindowCGBPal6c0 32192
#define PtrWindowCGBPal6c1 895
#define PtrWindowCGBPal6c2 573
#define PtrWindowCGBPal6c3 0

/* Gameboy Color palette 7 */
#define PtrWindowCGBPal7c0 32767
#define PtrWindowCGBPal7c1 31
#define PtrWindowCGBPal7c2 10
#define PtrWindowCGBPal7c3 0

/* CGB palette entries. */
#define PtrWindowCGB0 7
#define PtrWindowCGB1 7
#define PtrWindowCGB2 7
#define PtrWindowCGB3 6
#define PtrWindowCGB4 2
#define PtrWindowCGB5 6
#define PtrWindowCGB6 6
#define PtrWindowCGB7 6
#define PtrWindowCGB8 6
#define PtrWindowCGB9 6
#define PtrWindowCGB10 6
#define PtrWindowCGB11 6
#define PtrWindowCGB12 6
#define PtrWindowCGB13 6
#define PtrWindowCGB14 6
/* Start of tile array. */
extern unsigned char PtrWindow[];

/* End of WINDOW.H */
